# Generated by Django 3.2.9 on 2021-12-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandwidth',
            fields=[
                ('channelid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('wavelength1', models.FloatField(blank=True, null=True)),
                ('wavelength2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bandwidth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('endpointid', models.AutoField(primary_key=True, serialize=False)),
                ('oxyvalue', models.FloatField(blank=True, null=True)),
                ('deoxyvalue', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'endpoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patientname', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=5, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patienttreatment',
            fields=[
                ('pexid', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'patienttreatment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('exerciseid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exercisetype', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'treatment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatmentbandwidth',
            fields=[
                ('exerciseid', models.OneToOneField(db_column='exerciseid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.treatment')),
            ],
            options={
                'db_table': 'treatmentbandwidth',
                'managed': False,
            },
        ),
    ]
